version: '3.8'

services:
  web:
    build:
      context: MuzeyServer
    network_mode: "host"
    expose:
      - "8000"
    container_name: museum_app
    restart: always
    volumes:
      - ./MuzeyServer/static:/app/static
      - ./MuzeyServer/logfile.log:/app/logfile.log
