version: '3.8'

services:
  web:
    build:
      context: MuzeyServer
    expose:
      - "8000"
    ports:
      - "8000:8000"
    container_name: museum_app
    restart: always
    volumes:
      - ./MuzeyServer/static:/app/static
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: >
      sh -c "until pg_isready; do sleep 1; done;
      psql -U postgres -c 'CREATE DATABASE museum;'"

volumes:
  postgres_data:
