version: '3.8'

services:
  web:
    build:
      context: MuzeyServer
    expose:
      - "8000"
    ports:
      - "8000:8000"
    container_name: museum_app
    restart: always
    volumes:
      - ./MuzeyServer/static:/app/static
