# Generated by Django 4.2.17 on 2025-03-16 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='PlayerProfile',
        ),
    ]
