# Generated by Django 4.2.17 on 2025-03-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Полное ФИО')),
                ('nazvanie', models.CharField(choices=[('LTZ', 'ЛТЗ'), ('Mashzavod', 'Машзавод'), ('Agregatny_zavod', 'Агрегатный завод'), ('HleboKombinat', 'Хлебокомбинат'), ('Ludinovokabel', 'Людиновокабель'), ('Shveynaya_fabrika', 'Швейная фабрика'), ('OEZ', 'ОЭЗ'), ('SCHZ', 'СЧЗ'), ('other', 'Другое')], max_length=50, unique=True, verbose_name='название предприятия')),
                ('biography', models.TextField(blank=True, verbose_name='Биография/Информация')),
                ('image1', models.ImageField(blank=True, upload_to='static/assets/images', verbose_name='Изображение (главное)')),
                ('image2', models.ImageField(blank=True, upload_to='static/assets/images', verbose_name='Дополнительное изображение(1)')),
                ('image3', models.ImageField(blank=True, upload_to='static/assets/images', verbose_name='Дополнительное изображение(2)')),
                ('image4', models.ImageField(blank=True, upload_to='static/assets/images', verbose_name='Дополнительное изображение(3)')),
                ('image5', models.ImageField(blank=True, upload_to='static/assets/images', verbose_name='Дополнительное изображение(4)')),
            ],
            options={
                'verbose_name': 'работник предприятий',
                'verbose_name_plural': 'работники предприятий',
            },
        ),
    ]
