# Generated by Django 5.1.4 on 2025-01-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SearchResult", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="image1",
            field=models.ImageField(blank=True, upload_to="static/assets/images"),
        ),
        migrations.AlterField(
            model_name="person",
            name="image2",
            field=models.ImageField(blank=True, upload_to="static/assets/images"),
        ),
        migrations.AlterField(
            model_name="person",
            name="image3",
            field=models.ImageField(blank=True, upload_to="static/assets/images"),
        ),
        migrations.AlterField(
            model_name="person",
            name="image4",
            field=models.ImageField(blank=True, upload_to="static/assets/images"),
        ),
        migrations.AlterField(
            model_name="person",
            name="image5",
            field=models.ImageField(blank=True, upload_to="static/assets/images"),
        ),
    ]
