# Generated by Django 4.2.17 on 2025-03-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SearchResult', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='years_of_life',
            field=models.TextField(blank=True),
        ),
    ]
