# Generated by Django 5.1.6 on 2025-03-19 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SearchResult', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='image1',
            new_name='image_main',
        ),
        migrations.RemoveField(
            model_name='person',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='person',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='person',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='person',
            name='image5',
        ),
        migrations.CreateModel(
            name='ImagePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.ImageField(blank=True, upload_to='static/assets/images', verbose_name='Изображение (главное)')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='SearchResult.person', verbose_name='Работник')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
