# Generated by Django 4.2.17 on 2025-03-16 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SearchResult', '0002_person_years_of_life'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='years_of_life',
        ),
    ]
