# Generated by Django 4.2.17 on 2025-02-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SearchResult', '0002_alter_person_image1_alter_person_image2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='years_of_life',
        ),
        migrations.AddField(
            model_name='person',
            name='nazvanie',
            field=models.CharField(choices=[('LTZ', 'ЛТЗ'), ('Mashzavod', 'Машзавод'), ('Agregatny_zavod', 'Агрегатный завод'), ('HleboKombinat', 'Хлебокомбинат'), ('Ludinovokabel', 'Людиновокабель'), ('Shveynaya_fabrika', 'Швейная фабрика'), ('OEZ', 'ОЭЗ')], default=2, max_length=50, unique=True, verbose_name='Название предприятия'),
            preserve_default=False,
        ),
    ]
