# Generated by Django 4.2.17 on 2025-02-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SearchResult', '0003_remove_person_years_of_life_person_nazvanie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='biography',
            field=models.TextField(blank=True, verbose_name='Биография/Информация'),
        ),
        migrations.AlterField(
            model_name='person',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Полное ФИО'),
        ),
        migrations.AlterField(
            model_name='person',
            name='image1',
            field=models.ImageField(blank=True, upload_to='static/assets/images', verbose_name='Изображение (главное)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='image2',
            field=models.ImageField(blank=True, upload_to='static/assets/images', verbose_name='Дополнительное изображение(1)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='image3',
            field=models.ImageField(blank=True, upload_to='static/assets/images', verbose_name='Дополнительное изображение(2)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='image4',
            field=models.ImageField(blank=True, upload_to='static/assets/images', verbose_name='Дополнительное изображение(3)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='image5',
            field=models.ImageField(blank=True, upload_to='static/assets/images', verbose_name='Дополнительное изображение(4)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='nazvanie',
            field=models.CharField(choices=[('LTZ', 'ЛТЗ'), ('Mashzavod', 'Машзавод'), ('Agregatny_zavod', 'Агрегатный завод'), ('HleboKombinat', 'Хлебокомбинат'), ('Ludinovokabel', 'Людиновокабель'), ('Shveynaya_fabrika', 'Швейная фабрика'), ('OEZ', 'ОЭЗ'), ('other', 'Другое'), ('SCHZ', 'СЧЗ')], max_length=50, unique=True, verbose_name='Название предприятия'),
        ),
    ]
